export const GET_VERSION = "GET_VERSION";
export const LISTER_PACKAGES = "LISTER_PACKAGES";
export const SHOW_PACKAGE = "SHOW_PACKAGE";
export const INSTALL_PACKAGE = "INSTALL_PACKAGE";

export const APP_VERSION = "APP_VERSION";