# This is a basic workflow to help you get started with Actions

name: Build Windows

on:
  push:
    tags:
    - 'v*'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1.4.2

    - name: Build
      run: |
        npm i -g yarn@1.22.4
        yarn        
        yarn electron:build
        mkdir artifact-setup
        mv dist_electron/winget-ui\ Setup\ *.exe artifact-setup/

    - uses: actions/upload-artifact@master
      name: Upload installer
      with:
        name: Installer
        path: artifact-setup
